apiVersion: 1

policies:
  - orgId: 1
    receiver: slack-default
    group_by:
      - alertname
      - service
    routes:
      - receiver: telegram-default
        object_matchers:
          - - severity
            - =
            - critical
